# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3582393855d1998e92fe36c1339a2ed9bc6a16ddba2718053d9cca30a2c580557aa4a817c4098a65b119b207c740ba8837548452b90c2aeac4e26b9d918eaf1

test:
  secret_key_base: 633f25742b0746b840d897b592998adec3da63f186d6be118edaf99a191bddda3e6aa783ce3ee015bafafc281b01bf2f6b8db5b7734af332c1fca42cb2311242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
